name: habit_tracker
description: "A habit tracking app with GitHub-style heatmap visualization"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # HTTP requests
  http: ^1.1.2

  # Local storage
  shared_preferences: ^2.2.2

  # Date utilities
  intl: ^0.19.0

  # UI components
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/

  # App Icon (you can add your custom icon later)
  # flutter_icons:
  #   android: "launcher_icon"
  #   ios: true
  #   image_path: "assets/icon/icon.png"